### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by atolbert01** [atolbert01/LatchKey#27]
Unit testing involves instantiating game objects in the code and doing bare-bones tests to ensure that the interaction between objects is working correctly at a fundamental level. This will not replace functional testing though, as many of the tests are environment specific. The purpose of these are to quickly determine the code's basic functionality after making changes.

**Comment by jmagnes2** [comment]
Unit testing was postponed from starting in phase 1 to phase 2.

**Comment by jmagnes2** [comment]
Changing this to integration testing.
