### ISSUE TITLE
Integrate Team Logo Splash Screen

### ISSUE THREAD

**Issue by atolbert01** [atolbert01/LatchKey#37]
This scene needs to be integrated into the next build. It should be the first scene that is loaded. When the scene loads it should display the logo, wait a second or two and then load the next (intro) scene.

**Comment by Archangel8737** [comment]
Scenes integrated into build.  The scene loads and then after 10 seconds loads the next scene.  Also, if the user wants to skip splash screens they can press the ESC key.
